# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: default
  demands:
    # - agent.name == self-hosted-agent
    # <NAME> -equals <VALUE>'
    - agent.name -equals self-hosted-agent


steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli@latest
    npm install
    ng build --prod
  displayName: 'npm install and build'

# # trigger:
# - master

# pool:
#   vmImage: 'ubuntu-latest'

# steps:
# - task: NodeTool@0
#   inputs:
#     versionSpec: '10.x'
#   displayName: 'Install Node.js'

# - script: |
#     npm install -g @angular/cli
#     npm install
#     ng build --prod
#   displayName: 'npm install and build'